# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('password', models.CharField(default=b'e10adc3949ba59abbe56e057f20f883e', max_length=32)),
                ('department', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='check.Department')),
            ],
        ),
    ]
