# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='time',
            field=models.IntegerField(),
        ),
    ]
