# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-14 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_auto_20170406_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.BooleanField(default=0),
        ),
    ]
