# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_person_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
