# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.BooleanField(choices=[(1, '\u7537'), (2, '\u5973')], default=0),
        ),
    ]
